sudo: false
language: ruby
rvm:
- 2.4.1
before_install: gem install bundler -v 1.15.4
deploy:
  provider: rubygems
  api_key:
    secure: IGztrc71SZ6X3uMHT+RkrqRaHGihyq8Ikt80FfQEfC7CEsIJQtScOr8+Edqs0GRJfDBhV2WikUdUvMVvq9hZeiO0bJf4QMVTbh5cUIq5A+IP2T6nDwQZvlTO03vxMGunnCaF9MDqSTtA39VtIQJUlV5S3J2pv8oShBGB9CMffaB+LdzTw49fdKBc1TfBo6du8X1ELJPxx2ZmT0+0XAqxD0+lJ1x08T2XOfb2/iLmD/Yhg5+EPOuDY2ePO+PqSTJuiyKsFLxxKgjI1eVRwfvqKeSuFeFMxrj+CqA2+9aF8M28J4FIXac3U5obJYgPxmZznmqlPlh8fLamBZ2yZ/AVRfJIwSeYgAzTbo8te+bOpwwAk/+lMOzxkz82yK3bf2R9cnKY09lH2Uht3hkBWE5IUijfl4j34mvQl7JJJP6ZQHGg1v2pcAgXRlRQw60M2v4v8XFxOhdO39lMymyRXol1Raq3N4eY8AcxPa/GVPfR2/H4u9JDA1dUqsYxTO3LcfIZjs68q801Z3ddxLhOECOH0b8VfvCTibnVUOj8XpP/E0VUoXyjQ8mPancblfsy5BL9c8HB9Vim1ZcdmZ3FKbJ2Ud/dVxQmbMRW9doVL7dZMDbfxIuPEVfqTsssGucJByNeSXJzc+fMej5HCrCTpuOztOIgsT/JbxJQ6/e0IVL5F18=
  gem: idlc-sdk-core
  on:
    tags: true
    repo: NathanTCz/idlc-sdk-core
